# Generated by Django 5.1.4 on 2026-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('document', 'Dokumen'), ('schedule', 'Jadwal')], max_length=16)),
                ('source_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('lecturer_id', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('active', 'Aktif'), ('archived', 'Diarsipkan'), ('deleted', 'Dihapus')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
