# Generated by Django 5.1.4 on 2026-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimbingan_aktif_id', models.IntegerField()),
                ('uploaded_by', models.IntegerField()),
                ('document_type', models.CharField(choices=[('proposal', 'Proposal'), ('final_report', 'Laporan Akhir')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('uploaded', 'Diunggah'), ('verified', 'Terverifikasi'), ('rejected', 'Ditolak')], default='draft', max_length=16)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
