# Generated by Django 5.1.4 on 2026-05-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimbingan_aktif_id', models.IntegerField()),
                ('lecturer_id', models.IntegerField()),
                ('event_type', models.CharField(choices=[('guidance', 'Bimbingan'), ('defense', 'Sidang')], default='guidance', max_length=16)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Dijadwalkan'), ('ongoing', 'Berlangsung'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
