# Generated by Django 5.1.4 on 2026-05-21 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeSemester',
            fields=[
                ('periode_semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_periode', models.CharField(max_length=100)),
                ('status_periode', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='nonaktif', max_length=10)),
            ],
            options={
                'db_table': 'periode_semester',
            },
        ),
        migrations.CreateModel(
            name='Topik',
            fields=[
                ('topik_id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255, unique=True)),
                ('deskripsi', models.TextField()),
                ('prasyarat', models.TextField()),
                ('kuota', models.IntegerField()),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topik.periodesemester')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'dosen'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'topik',
            },
        ),
    ]
