# Generated by Django 5.1.4 on 2026-05-21 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topik', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanKP',
            fields=[
                ('pengajuan_kp_id', models.AutoField(primary_key=True, serialize=False)),
                ('judul_diajukan', models.CharField(max_length=255)),
                ('deskripsi_sistem', models.TextField(help_text='Abstrak atau gambaran umum sistem yang akan dibuat')),
                ('status_pengajuan', models.CharField(choices=[('pending', 'Pending'), ('disetujui_pembimbing', 'Disetujui Pembimbing'), ('disetujui_koordinator', 'Disetujui Koordinator'), ('ditolak', 'Ditolak')], default='pending', max_length=25)),
                ('catatan', models.TextField(blank=True, help_text='Catatan revisi dari dosen atau koordinator', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(limit_choices_to={'role': 'mahasiswa'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topik.topik')),
            ],
            options={
                'db_table': 'pengajuan_kp',
            },
        ),
    ]
