# Generated by Django 6.0.5 on 2026-05-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuankp',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pengajuankp',
            name='deskripsi_sistem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pengajuankp',
            name='status_pengajuan',
            field=models.CharField(default='draft', max_length=25),
        ),
    ]
