# Generated by Django 6.0.5 on 2026-05-28 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengajuan', '0002_alter_pengajuankp_catatan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BimbinganAktif',
            fields=[
                ('bimbingan_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bimbingan_dosen', to=settings.AUTH_USER_MODEL)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bimbingan_mhs', to=settings.AUTH_USER_MODEL)),
                ('pengajuan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bimbingan_aktif', to='pengajuan.pengajuankp')),
            ],
            options={
                'db_table': 'bimbingan_aktif',
            },
        ),
        migrations.CreateModel(
            name='ProsesPenentuan',
            fields=[
                ('proses_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('menunggu', 'menunggu'), ('disetujui', 'disetujui'), ('ditolak', 'ditolak')], default='menunggu', max_length=20)),
                ('tahap_chain', models.CharField(choices=[('koordinator', 'koordinator'), ('dosen', 'dosen'), ('kaprodi', 'kaprodi'), ('selesai', 'selesai')], default='koordinator', max_length=20)),
                ('catatan_penolakan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosen_diusulkan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usulan_bimbingan', to=settings.AUTH_USER_MODEL)),
                ('pengajuan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proses_penentuan', to='pengajuan.pengajuankp')),
            ],
            options={
                'db_table': 'proses_penentuan',
            },
        ),
    ]
